# Generated by Django 3.0.4 on 2020-05-17 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssites',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
